# Generated by Django 6.0.7 on 2026-07-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='questions',
        ),
        migrations.AddField(
            model_name='certificate',
            name='json_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
